version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pwd
    volumes:
      - mysql_data:/var/lib/mysql
  apache:
    build: ./apache
    ports:
      - "8080:80"

volumes:
  mysql_data:
